### ISSUE TITLE
脚本一开始无法运行

### ISSUE THREAD

**Issue by moanxian** [HirokiChin/CqoocAutoCompleteCourse#16]
脚本一运行就出现下面的报错，然后用cmd或者直接点开的话就直接闪退
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\学习\CqoocAutoCompleteCourse-master\cqooc.py", line 572, in <module>
    AutoCompleteOnlineCourse().main()
  File "C:\Users\86180\Desktop\学习\CqoocAutoCompleteCourse-master\cqooc.py", line 433, in main
    self.CompleteCourse = self.getCompleteCourse()
  File "C:\Users\86180\Desktop\学习\CqoocAutoCompleteCourse-master\cqooc.py", line 496, in getCompleteCourse
    for i in data.json()['data']:
  File "C:\Users\86180\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\86180\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\86180\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\86180\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> 
![HQ`NSB~D@NERXAI SCAPL(3](https://user-images.githubusercontent.com/85947435/122069427-c50de280-ce27-11eb-96b5-eb5bf34e7161.png)

**Comment by 1773022941** [comment]
我也是这样
