### ISSUE TITLE
题目作答（过期题目作答）功能失效

### ISSUE THREAD

**Issue by censujiang** [HirokiChin/CqoocAutoCompleteCourse#33]
报错提示：
```bash
Traceback (most recent call last):
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 590, in <module>
    AutoCompleteOnlineCourse().main()
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 436, in main
    autoCompletPapers.sendAnswers(mode='due')
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 312, in sendAnswers
    answers = self.getAnswers(id) if mode == 'due' else self.getAnswersFromUser(id)
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 225, in getAnswers
    ids = self.getIds(paperId)
  File "d:\git\HirokiChin\CqoocAutoCompleteCourse\cqooc.py", line 81, in getIds
    "sid": self.sectionList.get(data.get('parentId'))[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by HirokiChin** [comment]
邮箱留下，晚些时候有空与你联系

**Comment by censujiang** [comment]
dfjsiou@qq.com
