### ISSUE TITLE
请问这是...

### ISSUE THREAD

**Issue by greg-wong** [HirokiChin/CqoocAutoCompleteCourse#4]
```
 Traceback (most recent call last):
  File "C:/Users/（用户名）/Desktop/cqooc.py", line 166, in <module>
    AutoCompleteOnlineCourse().main()
  File "C:/Users/（用户名）/Desktop/cqooc.py", line 57, in main
    self.startLearnCourse()
  File "C:/Users/（用户名）/Desktop/cqooc.py", line 153, in startLearnCourse
    index_t + 1, len(sectionList.items()), ((float((index_t + 1) / len(sectionList.items()))) * 100),self.courseDes[chapterId]))
KeyError: '128654'

```

出现了这个错误，而且只刷成功了这个课的一部分

**Comment by HirokiChin** [comment]
使用最新的文件，已修复此问题！
