### ISSUE TITLE
拷贝答案作答在哪里输入别人的cookie，一输入3脚本就运行完了

### ISSUE THREAD

**Issue by gsymasd** [HirokiChin/CqoocAutoCompleteCourse#6]

**Comment by HirokiChin** [comment]
请使用最新版本再试试，如仍有此问题，请使用终端/CMD运行一次，然后截图谢谢

**Comment by xiuxiudada** [comment]
作者大大，我也是这个问题，不知道图片怎么上传，我的邮箱是mimosaxiu@qq.com，麻烦您。。

**Comment by HirokiChin** [comment]
联系方式已经发你邮箱了，加一下我

**Comment by 01100001011** [comment]
我也这样。用cmd运行就直接退出，用pytharm运行就显示下面这个
Traceback (most recent call last):
  File "C:\python\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\脚本\cqgxzx.py", line 590, in <module>
    AutoCompleteOnlineCourse().main()
  File "D:\脚本\cqgxzx.py", line 438, in main
    autoCompletPapers.sendAnswers()
  File "D:\脚本\cqgxzx.py", line 300, in sendAnswers
    }).json()['data'][0]['id']
  File "C:\python\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

**Comment by 01100001011** [comment]
题目作答运行后是下面这样的，怎么解决。
1、模拟观看网课
2、题目作答（过期题目作答）
3、题目作答（拷贝答案作答）
4、导出题目与答案

请选择模式（序号）: 3
Traceback (most recent call last):
  File "C:\python\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\脚本\cqgxzx.py", line 590, in <module>
    AutoCompleteOnlineCourse().main()
  File "d:\脚本\cqgxzx.py", line 438, in main
    autoCompletPapers.sendAnswers()
  File "d:\脚本\cqgxzx.py", line 300, in sendAnswers
    }).json()['data'][0]['id']
  File "C:\python\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
